apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sealed-secret-namespace.yaml
- sealed-secrets.yaml

# Installs sealed-secrets to its own namespace instead of the default "kube-system".
patchesJson6902:
- target:
    group: "apps"
    version: v1
    kind: Deployment
    name: sealed-secrets-controller
    namespace: sealed-secrets
  path: patch.yaml