apiVersion: v1
data:
  htpasswd: YWRtaW46JDJ5JDA1JFdKU2FrajQwY1F4dGNKMERpdlpidmVaOFJNeHA0RzQ5eFNQakx2YzJPRzcvR0hGeTdxYWJtCmRldmVsb3BlcjokMnkkMDUkQzRucHNQdURteThOVDFoQVRWb2Q1LnRCV1EuWGRHQkpEeHBOUVgvelhhMFp2NHpKNENhQk8KdGVzdGVyOiQyeSQwNSRBT2xpb1haLzdLVTRLdW1aY0NZR0UuOTc4c2JpemhkdnFWZUllTkxVdkwuL0E3dEpJd0J0bQo=
kind: Secret
metadata:
  creationTimestamp: null
  name: htpass-secret
  namespace: openshift-config