apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/applications/sealed-secrets/kustomization.yaml
- ../base/configs/rbac/kustomization.yaml
- ../base/configs/htpasswd/kustomization.yaml
